### ISSUE TITLE
nsp throws "Regular Expression Denial of Service" for debug

### ISSUE THREAD

**Issue by slahiri** [Parsimotion/winston-azure-blob-transport#5]
Regular Expression Denial of Service
Name          │ debug                                                                                                │
CVSS          │ 3.7 (Low)                                                                                            │
Installed     │ 2.2.0                                                                                                │
Vulnerable    │ <= 2.6.8 || >= 3.0.0 <= 3.0.1                                                                        │
Patched       │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                                                         │
More Info     │ https://nodesecurity.io/advisories/534                                                               │

**Comment by gastonprieto** [comment]
Done, thank you. 66d3ab4
